context:
  name: opencode
  version: "1.1.35"
  repo: anomalyco/opencode

package:
  name: ${{ name }}
  version: ${{ version }}

source:
    url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-linux-x64.tar.gz
    sha256: 451f5a36e2875b5540adf55e8cc9e144902b44959a6f31899fc21876b38b31ae
    file_name: opencode.tar.gz

build:
  number: 0
  script: |
    tar xvf opencode.tar.gz
    mkdir -p $PREFIX/bin
    mv opencode $PREFIX/bin/opencode
    chmod 755 $PREFIX/bin/opencode
    
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false

requirements:
  build:  
    - tar

tests:
  - script:
      - opencode -h

about:
  homepage: https://opencode.ai/
  license: MIT
  summary: 'The open source coding agent.'
  description: |
    The open source coding agent.
  repository: https://github.com/anomalyco/opencode
