context:
  name: opencode
  version: 1.1.35
  repo: anomalyco/opencode
  # 对应的 Pixi 定义的平台
  platform: ${{ env.get("TARGET_PLATFORM", default="linux-64") }}
  # 对应包的名称
  architect: ${{ "linux-x64" if platform == "linux-64" else "linux-arm64" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
    url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-${{ architect }}.tar.gz
    sha256: ...
    file_name: opencode.tar.gz

build:
  number: 0
  script: |
    tar xvf opencode.tar.gz
    mkdir -p $PREFIX/bin
    mv opencode $PREFIX/bin/opencode
    chmod 755 $PREFIX/bin/opencode
    
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false

requirements:
  build:  
    - tar

tests:
  - script:
      - opencode -h

about:
  homepage: https://opencode.ai/
  license: MIT
  summary: 'The open source coding agent.'
  description: |
    The open source coding agent.
  repository: https://github.com/anomalyco/opencode
