context:
  name: devpod
  version: 1
  repo: skevetter/devpod
  # 对应的 Pixi 定义的平台
  platform: ${{ env.get("TARGET_PLATFORM", default="linux-64") }}
  # 对应包的名称
  architect: ${{ "linux-amd64" if platform == "linux-64" else "linux-arm64" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
    url: https://github.com/${{ repo }}/releases/download/v${{ version }}/devpod-${{ architect }}
    sha256: ...
    file_name: devpod

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    mv devpod $PREFIX/bin/devpod
    chmod 755 $PREFIX/bin/devpod
    
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false

tests:
  - script:
      - devpod -h

about:
  homepage: https://github.com/skevetter/devpod
  license: Mozilla Public License Version 2.0
  summary: 'Open-source devcontainers: works with any IDE and lets you use any cloud, kubernetes or just localhost docker.'
  description: |
    Open-source devcontainers: works with any IDE and lets you use any cloud, kubernetes or just localhost docker.
  repository: https://github.com/skevetter/devpod
