context:
  name: devpod
  version: 1
  repo: skevetter/devpod
  # 对应的 Pixi 定义的平台
  platform: ${{ env.get("TARGET_PLATFORM", default="linux-64") }}
  # 对应包的名称
  architect: ${{ "linux-amd64" if platform == "linux-64" else "linux-arm64" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
    url: https://github.com/${{ repo }}/releases/download/v${{ version }}/devpod-${{ architect }}
    sha256: ...
    file_name: devpod

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    mv devpod $PREFIX/bin/devpod
    chmod 755 $PREFIX/bin/devpod
    
  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false

requirements:
  build:  
    - tar

tests:
  - script:
      - opencode -h

about:
  homepage: https://opencode.ai/
  license: MIT
  summary: 'The open source coding agent.'
  description: |
    The open source coding agent.
  repository: https://github.com/anomalyco/opencode
