context:
  name: mihomo-bin
  version: 1
  repo: MetaCubeX/mihomo
  # 对应的 Pixi 定义的平台
  platform: ${{ env.get("TARGET_PLATFORM", default="linux-aarch64") }}
  # 对应包的名称
  architect: ${{ "linux-amd64-compatible" if platform == "linux-64" else "linux-arm64" }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
    url: https://github.com/${{ repo }}/releases/download/v${{ version }}/mihomo-${{ architect }}-v${{ version }}.gz
    sha256: ...
    file_name: mihomo.gz

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    gzip -d mihomo.gz
    mv mihomo $PREFIX/bin/mihomo
    chmod 755 $PREFIX/bin/mihomo

  prefix_detection:
    ignore_binary_files: true
  dynamic_linking:
    binary_relocation: false

requirements:
  build:  
    - gzip

tests:
  - script:
      - mihomo -h

about:
  homepage: https://github.com/MetaCubeX/mihomo
  license: GPL-3.0-only
  summary: 'Mihomo Kernel.'
  description: |
    Mihomo Kernel.
  repository: https://github.com/MetaCubeX/mihomo
